data_path: ./datas/store/mid1
headless: true
device: linux
# 一个投稿机器人🤖️
video_dir: ./datas/vds/mp42/
ph_dir: ./datas/vds/ph/

linux_chrome_path: /usr/bin/google-chrome

mac_chrome_path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

# video
video_prefix: 【步非烟音声】

key_words:
    - 步非烟
    - 文静音声
    - 步非烟中文音声
    - 步非烟音声
    - 音声步非烟
    - 中文音声
    - 明前奶绿
    - 步非烟音声
    - 男性向

# 用于发给自己视频的。
self_comments:
    - 暗号：“已三连”，拿收集de二十万音声合集[大笑]
    - 收藏带师来了，跟队形:“已三连”，拿收集de二十万音声合集[大笑]
    - 三联+关🐷,斯我拿/盒集.队形：“已三连”
    - 斯我拿/盒集.队形：“已三连”
    - 叩我,bF烟第三季/所有.
    - 三联+关🐷,斯_我_"1"_，拿_合_集[🤪]
    - 三联+关🐷,斯❤️扣1，有东西,

# 广告语录
comments:
    - 斯我拿/合集.
    - 斯我拿/盒集.
    - 扣我拿/盒集.
    - 扣我拿/盒集 音声.
    - 叩我拿/盒集.
    - 叩我获取/盒集.
    - 斯信扣1拿盒集.前提是三连！所以大家下面排队形：
    - 叩我,第三季/所有.
    - 扣1➕关注拿第三季. yoU will get bu_fei_yån 第三季所有.
    - 我第一个视频三联+关🐷, 斯信扣1拿盒集
    - 音声，扣我白嫖,
    - 斯/我/"1"/，拿/合/集[🤪]
    - 扣1拿

# 随机前缀.
prefix:
    - 咳咳,[大笑]
    - 懂懂都懂[大笑]
    - 三连然后斯我扣1,拿第三季bfy
    - 这里，
    - 来了来了
    - 音声玩家来了，
    - up视频不错,
    - 哼哼，啊啊啊啊啊啊啊,
    - 全体目光像我看齐嗷,
    - 懂得都懂
